# Generated by Django 4.0.4 on 2022-04-16 22:21

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uf',
            field=localflavor.br.models.BRStateField(default='', max_length=2, null=True),
        ),
    ]
