# Generated by Django 4.0.3 on 2022-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_foto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_user',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/fotos/%d/%m/%Y'),
        ),
    ]
