# Generated by Django 4.0.3 on 2022-03-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cep_user_endereco_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
