# Generated by Django 4.0.3 on 2022-03-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='foto_user',
        ),
    ]
