# Generated by Django 4.0.3 on 2022-03-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_foto_user_foto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_user',
            field=models.ImageField(blank=True, default='', upload_to='fotos/%d/%m/%Y'),
        ),
    ]
