# Generated by Django 4.0.3 on 2022-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_foto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mensagem',
            field=models.TextField(default='', max_length=480),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_user',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
