# Generated by Django 4.0.3 on 2022-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_mensagem_alter_user_foto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mensagem',
            field=models.TextField(blank=True, default='', max_length=480),
        ),
    ]
