# Generated by Django 4.0.3 on 2022-03-19 16:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('preco_produto', models.FloatField()),
                ('quantidade_produto', models.IntegerField(default=0)),
                ('descricao_produto', models.TextField(max_length=500)),
                ('disponivel', models.BooleanField(default=False)),
                ('fornecedor', models.CharField(max_length=50)),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
