# Generated by Django 4.0.3 on 2022-04-02 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=30)),
                ('cnpj_fornecedor', models.CharField(max_length=18)),
                ('endereco_fornecedor', models.CharField(max_length=150)),
                ('cep_fornecedor', models.CharField(default='', max_length=10, null=True)),
                ('cidade_fornecedor', models.CharField(max_length=30)),
                ('uf_fornecedor', models.CharField(max_length=2)),
                ('telefone_fornecedor', models.CharField(max_length=15)),
                ('email_fornecedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('marca_produto', models.CharField(max_length=50, null=True)),
                ('preco_produto', models.FloatField()),
                ('quantidade_produto', models.IntegerField(default=0)),
                ('descricao_produto', models.TextField(max_length=500, null=True)),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('fornecedor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.fornecedor')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_cliente', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('id_produto', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
                ('id_user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
