# Generated by Django 4.0.4 on 2022-04-16 20:42

from django.db import migrations, models
import produtos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome_fornecedor'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_fornecedor',
            field=models.CharField(max_length=18, validators=[produtos.validators.cnpj_valido]),
        ),
    ]
