# Generated by Django 4.0.3 on 2022-03-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=30)),
                ('cnpj_fornecedor', models.CharField(max_length=18)),
                ('endereco_fornecedor', models.CharField(max_length=150)),
                ('cidade_fornecedor', models.CharField(max_length=30)),
                ('uf_fornecedor', models.CharField(max_length=2)),
                ('telefone_fornecedor', models.CharField(max_length=15)),
                ('email_fornecedor', models.CharField(max_length=50)),
            ],
        ),
    ]
