# Generated by Django 4.0.3 on 2022-03-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
    ]
