# Generated by Django 4.0.3 on 2022-03-19 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_fornecedor_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='cep',
            new_name='cep_fornecedor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.fornecedor'),
        ),
    ]
