# Generated by Django 4.0.3 on 2022-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_cep_fornecedor_cep_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(max_length=30),
        ),
    ]
