# Generated by Django 4.0.3 on 2022-03-28 01:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0006_produto_marca_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(default='', max_length=15)),
                ('cep_cliente', models.CharField(default='', max_length=10)),
                ('endereco_cliente', models.CharField(default='', max_length=150)),
                ('cpf_cliente', models.CharField(default='', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('id_cliente', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.cliente')),
                ('id_produto', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
                ('id_user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
