# Generated by Django 4.0.3 on 2022-03-28 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0007_cliente_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='id_cliente',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
