# Generated by Django 4.0.3 on 2022-03-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_produto_preco_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('nome_produto',)},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
