# Generated by Django 4.0.3 on 2022-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_options_remove_produto_data_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
