# Generated by Django 4.0.3 on 2022-03-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(default='', max_length=15)),
                ('cep_cliente', models.CharField(default='', max_length=10)),
                ('endereco_cliente', models.CharField(default='', max_length=150)),
                ('cpf_cliente', models.CharField(default='', max_length=14)),
            ],
        ),
    ]
